# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12As_ZAhGnxjTxIgypo9Qjg7yAd7yJ3c7
"""



"""## Setup Environment and Mount Drive


"""

from google.colab import drive
drive.mount('/content/drive')

IMG_SIZE = (128, 128)
BATCH_SIZE = 64

print(f"Google Drive mounted successfully. IMG_SIZE set to {IMG_SIZE} and BATCH_SIZE set to {BATCH_SIZE}.")

"""## Load and Prepare Data


"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

DATASET_PATH = '/content/drive/MyDrive/Research_Project/dataset/drowsiness_data'

# Create an ImageDataGenerator for training with augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    horizontal_flip=True
)

# Create an ImageDataGenerator for validation (only rescaling)
val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Create training data generator
train_generator = train_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training'
)

# Create validation data generator
validation_generator = val_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation'
)

print("Training and validation data generators created successfully.")

"""## Build MobileNetV2 Model



"""

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model

# Define the input shape for the model
input_shape = (IMG_SIZE[0], IMG_SIZE[1], 3)

# Load the MobileNetV2 base model
base_model = MobileNetV2(input_shape=input_shape,
                           include_top=False,
                           weights='imagenet')

# Freeze the base model layers
base_model.trainable = False

# Create the classification head
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(1, activation='sigmoid')(x)

# Construct the full model
model = Model(inputs=base_model.input, outputs=predictions)

# Print model summary
model.summary()

print("MobileNetV2 model constructed and base model layers frozen successfully.")

"""## Compile and Train Model


"""

from tensorflow.keras.callbacks import EarlyStopping

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Define EarlyStopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

# Train the model
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10,
    callbacks=[early_stopping]
)

print("Model compiled and trained successfully. Training history stored in 'history' variable.")

model.save('drowsiness_model.h5')
print("Model saved as 'drowsiness_model.h5' successfully.")

import matplotlib.pyplot as plt

# Get training history
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(len(acc))

plt.figure(figsize=(12, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

print("Training history (accuracy and loss) plots displayed successfully.")

"""## Evaluate Model on Validation Data

"""

val_loss, val_accuracy = model.evaluate(validation_generator)
print(f"Validation Loss: {val_loss:.4f}")
print(f"Validation Accuracy: {val_accuracy:.4f}")

"""## Final Task

### Subtask:
Provide a conclusion on whether the model shows signs of overfitting based on the evaluation and analysis of the training history.

"""